### PR TITLE
WIP: add multi select for NFTs

### PR DESCRIPTION
**Pull request by aniruddhaaps**
WIP: Multi-select for 1sat ordinal NFTs

Draft implementation for:
- Select multiple NFTs
- Send to single address
- List at single price

Still TODO:
- Testing
- UI polish
- Error handling

Related: #4

### CODE REVIEW

**Comment by danwag06** [comment]
@aniruddhaaps How's it going. Do you think you will be able to finish or should we reassign?

**Comment by aniruddhaaps** [comment]
its going great sir, expect a final pr within 3 days maximum

**Comment by aniruddhaaps** [comment]
@danwag06 any documentation on how to get testnet tokens and test nfts

**Comment by danwag06** [comment]
@aniruddhaaps the main branch now has a way to get testnet coins directly in the wallet. Just create a testnet account.

Regarding test inscriptions/NFTS... spv-wallet-browser is a whitelabel of yours wallet. So you can use the following to inscribe. This can be done by opening dev tools on any browser page and in the console calling `await yours.connect()`.

Once connected you can call `await yours.inscribe()`

https://yours-wallet.gitbook.io/provider-api/ordinals/inscribe

**Comment by aniruddhaaps** [comment]
@danwag06 kindly review

**Comment by danwag06** [comment]
Hi @aniruddhaaps unfortunately this approach isn't going to work. We'd want to follow the existing patterns that exist in the codebase such as using styled-components over tailwind. Also there are certain methods being used that don't exists on the Yours provider. Given the time constraints of the hackathon and the amount of work still required to complete this issue, I'm going to mark this as closed.

Thanks for the effort!

**Pull request closed without merging**
