### PR TITLE
feat: Implement page state persistence for wallet window

### PR DESCRIPTION
**Pull request by Ekene001**

### CODE REVIEW

**Comment by danwag06** [comment]
@Ekene001 we've tested the current implementation and it's likely going to be problematic with how the provider api works (ie when third party applications invoke the wallet to do something, it's going to open in an incorrect state). The correct way to approach this would likely be to create some new context that works with/alongside the `Web3RequestContext` such that web3 requests that come 3rd party apps override any existing state settings.

It's also worth noting that it would be important to store any sort of form/input values.

**Given the time constraints for the hackathon, it may be worth trying to simplify this one.** 

At it's core, we really just want to persist state when a user is trying to enter a password. There are many people that use password managers and chrome doesn't make it easy to use these within extensions (maybe they do and I'm not aware). At the end of the day, we're looking to implement a solution specifically for the problem where a user needs to enter a password and by closing the app window, they lose their state.

A global search for ` type="password"` would reveal all the places where password is used.

**Comment by Ekene001** [comment]
@danwag06 good day sir, 
Okay sir I'll make the corrections and make a PR soon

**Comment by Ekene001** [comment]
- create PasswordInput component
- create PersistedPasswordInput component
- add PasswordPersistenceContext for managing password state
- update UnlockWallet component to use PasswordInput
- implement usePersistedPassword hook
- modify ChromeStorageService to handle password state
- update index.tsx to include PasswordPersistenceProvider

**Comment by danwag06** [comment]
@Ekene001 what is the state of this? We are going to conclude the hackathon. If you think you can get it across the finish line in the next day or so let me know. We tested the current implementation and it seems like it is still a WIP.

**Comment by Ekene001** [comment]
@danwag06 Okay, I’ll implement a feature to automatically clear the password from the state after 5 minutes to enhance security.
Once this is done, I think i am done with this. Please can you confirm ser
Yes I'll be done with this in the next 24 hrs .

**Comment by danwag06** [comment]
We've decided to close this issue. It doesn't seem like we're aligned with the requirement...

Be on the look out for a reward on only dust for your time. 🙏

**Pull request closed without merging**
